Added Whole System History API documentation to swagger and open api gen
IBM/FHIR pull request #3269
Opened 2022-02-02 15:07 UTC by mpayne2

Signed-off-by: mpayne2 <mpayne2@us.ibm.com>

2022-02-02 19:43 UTC, tbieste reviewed
When updating these, I think we also usually update /fhir-openapi/src/main/webapp/META-INF/openapi.json with the generated OpenAPI file as well.

2022-02-02 19:43 UTC, tbieste commented on fhir-swagger-generator/src/main/java/com/ibm/fhir/openapi/generator/FHIROpenApiGenerator.java
>      public static final String TYPEPACKAGENAME = "com.ibm.fhir.model.type";
Update copyright at top of file to "2018, 2022".

2022-02-02 19:43 UTC, tbieste commented on fhir-swagger-generator/src/main/java/com/ibm/fhir/swagger/generator/FHIRSwaggerGenerator.java
Update copyright at top of file to "2016, 2022".

2022-02-02 19:43 UTC, tbieste commented on fhir-swagger-generator/src/main/java/com/ibm/fhir/swagger/generator/FHIRSwaggerGenerator.java
> +//        generateDefinition(DomainResource.class, definitions);
Is this commented out line needed?

2022-02-02 20:23 UTC, mpayne2 commented
I'm not sure which generated open api file I should use to copy this into /fhir-openapi/src/main/webapp/META-INF/openapi.json.  The all-openapi.json has many more differences than what is in this file.

2022-02-02 21:14 UTC, tbieste approved these changes
LGTM

2022-02-03 13:29 UTC, lmsurpre requested changes
The code looks good, but when I us the generated openapi.json in Liberty it emits a bunch of warnings like the following:
```
[2/3/22, 13:24:45:907 UTC] 00000034 OpenAPIUtils  E   CWWKO1650E: Validation of the OpenAPI document produced the following error(s): 
                                 
 - Message: More than one Operation Objects with "_history" value for "operationId" field was found. The "operationId" must be unique among all operations described in the API, Location: #/paths/~1ActivityDefinition~1_history/get/operationId
 ```
 
 please address

2022-02-03 17:58 UTC, mpayne2 commented
I can't amend previous commits with the signoff.  Moving to a new pull request.

2022-02-03 17:58 UTC, closed without merging

2022-02-03 18:14 UTC, mpayne2 commented
New pull request:
https://github.com/IBM/FHIR/pull/3279